services:
  app:
    build: .
    container_name: poker-django

    # For production :
    # command: daphne -b 0.0.0.0 -p 80 poker_project.asgi:application

    # For dev :
    command: >
      watchmedo auto-restart 
      --directory=/code/poker 
      --patterns="*.py;*.html" 
      --recursive --
      daphne -b 0.0.0.0 -p 80 poker_project.asgi:application

    ports:
      - 80:80
    volumes:
      - .:/code
      - static_data:/code/poker/staticfiles
    # environment:
    #   - DJANGO_SETTINGS_MODULE=poker_project.settings
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: poker-redis
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes # Enable persistence

volumes:
  redis_data: # For Redis persistence
  static_data: # For Django static files
