# Generated by Django 5.1.5 on 2025-01-28 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_rename_money_won_profile_total_chips_received_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='average_decision_time',
        ),
    ]
