# Generated by Django 5.1.5 on 2025-01-30 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_game_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='code',
        ),
        migrations.AddField(
            model_name='game',
            name='betting_type',
            field=models.CharField(choices=[('limit', 'Limit'), ('no_limit', 'No-Limit')], default='no_limit', max_length=10),
        ),
        migrations.AddField(
            model_name='game',
            name='game_type',
            field=models.CharField(choices=[('texas_holdem', "Texas Hold'em")], default='texas_holdem', max_length=20),
        ),
        migrations.AddField(
            model_name='game',
            name='name',
            field=models.CharField(default='Nameless', max_length=25, unique=True),
        ),
    ]
