# Generated by Django 5.1.5 on 2025-01-30 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_player_last_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='password_reset_link',
            field=models.TextField(blank=True),
        ),
    ]
