# Generated by Django 5.1.5 on 2025-01-31 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_profile_password_reset_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='password_reset_link',
        ),
    ]
