# Generated by Django 5.1.5 on 2025-01-31 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_remove_profile_password_reset_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(max_length=25),
        ),
    ]
