# Generated by Django 5.1.5 on 2025-02-01 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_alter_profile_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='nickname',
        ),
    ]
