# Generated by Django 5.1.5 on 2025-02-01 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_remove_profile_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='dealer_position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
