# Generated by Django 5.1.5 on 2025-02-01 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_game_dealer_position_player_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='current_turn',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
