# Generated by Django 5.1.5 on 2025-02-10 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_alter_game_current_turn_alter_game_dealer_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='current_turn',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
