# Generated by Django 5.1.5 on 2025-02-12 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_alter_game_current_turn'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='hole_cards',
            field=models.JSONField(default=list),
        ),
    ]
