# Generated by Django 5.1.5 on 2025-02-17 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0018_alter_game_game_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='betting_type',
            field=models.CharField(choices=[('no_limit', 'No-Limit')], default='no_limit', max_length=10),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_type',
            field=models.CharField(choices=[('sit_and_go', "Texas Hold'em - Sit & Go")], default='sit_and_go', max_length=20),
        ),
    ]
