# Generated by Django 5.1.5 on 2025-02-17 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0019_alter_game_betting_type_alter_game_game_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(default='Waiting', max_length=20),
        ),
    ]
