# Generated by Django 5.1.5 on 2025-02-17 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0020_alter_game_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='current_bet',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='has_folded',
            field=models.BooleanField(default=False),
        ),
    ]
