# Generated by Django 5.1.5 on 2025-02-17 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0021_player_current_bet_player_has_folded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='is_ready',
        ),
    ]
