# Generated by Django 5.1.5 on 2025-02-18 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0022_remove_player_is_ready'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='pot',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
