# Generated by Django 5.1.5 on 2025-02-18 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0023_game_pot'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='current_phase',
            field=models.CharField(choices=[('preflop', 'Preflop'), ('flop', 'Flop'), ('turn', 'Turn'), ('river', 'River'), ('showdown', 'Showdown')], default='preflop', max_length=10),
        ),
    ]
