# Generated by Django 5.1.5 on 2025-02-18 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0024_game_current_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
