# Generated by Django 5.1.5 on 2025-02-18 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0025_player_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='is_active',
        ),
    ]
