# Generated by Django 5.1.5 on 2025-02-18 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0026_remove_player_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='deck',
            field=models.JSONField(default=list),
        ),
    ]
