# Generated by Django 5.1.5 on 2025-02-20 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0027_game_deck'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='community_cards',
            field=models.JSONField(default=list),
        ),
    ]
