# Generated by Django 5.1.5 on 2025-02-20 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0028_player_community_cards'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='community_cards',
        ),
        migrations.AddField(
            model_name='game',
            name='community_cards',
            field=models.JSONField(default=list),
        ),
    ]
