# Generated by Django 5.1.5 on 2025-02-20 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0029_remove_player_community_cards_game_community_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='has_checked',
            field=models.BooleanField(default=False),
        ),
    ]
