# Generated by Django 5.1.5 on 2025-03-02 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0031_alter_game_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='last_bet_amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
