# Generated by Django 5.1.5 on 2025-03-02 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0032_game_last_bet_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='last_bet_amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
