# Generated by Django 5.1.5 on 2025-03-06 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0034_alter_game_last_bet_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='current_min_raise',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
