# Generated by Django 5.1.5 on 2025-03-06 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0035_game_current_min_raise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='current_min_raise',
        ),
    ]
