# Generated by Django 5.1.5 on 2025-03-08 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0036_remove_game_current_min_raise'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_all_in',
            field=models.BooleanField(default=False),
        ),
    ]
