# Generated by Django 5.1.5 on 2025-03-08 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0037_player_is_all_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='total_bet',
            field=models.IntegerField(default=0),
        ),
    ]
