# Generated by Django 5.1.5 on 2025-03-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0038_player_total_bet'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='side_pots',
            field=models.JSONField(default=list),
        ),
    ]
