# Generated by Django 5.1.5 on 2025-03-09 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0039_game_side_pots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='pot',
        ),
    ]
