# Generated by Django 5.1.5 on 2025-03-11 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0040_remove_game_pot'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='has_acted_this_round',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='is_big_blind',
            field=models.BooleanField(default=False),
        ),
    ]
