# Generated by Django 5.1.5 on 2025-03-11 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0041_player_has_acted_this_round_player_is_big_blind'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='last_bet_amount',
        ),
    ]
