# Generated by Django 5.1.5 on 2025-03-22 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0042_remove_game_last_bet_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_dealer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='is_small_blind',
            field=models.BooleanField(default=False),
        ),
    ]
