# Generated by Django 5.1.5 on 2025-03-24 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0044_player_is_nexttoplay'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='is_nextToPlay',
            new_name='is_next_to_play',
        ),
    ]
