# Generated by Django 5.1.5 on 2025-03-25 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0045_rename_is_nexttoplay_player_is_next_to_play'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='is_next_to_play',
        ),
    ]
